export { default as Login } from './login'
export { default as Dashboard} from './dashboard'
export { default as Account } from './account'
export { default as KhoanThu } from './khoanthu'
export { default as NhanKhau } from './nhankhau'
export { default as NopTien }  from './noptien'
export { default as TamTru } from './tamtru'